- Components/Search/FilterOpenChat.tsx
- Components/Search/OpenChatPicture.tsx
- Components/Search/OpenChatText.tsx
- Components/Search/SearchOpenChat.tsx
- Components/Search/ShowAllOpenChat.tsx
- app/search/page.tsx
- app/search/search.type.ts
- app/search/search.utils.ts
#close #7
Feat : 모든 오픈 채팅방 목록 화면에 보여주기 
1. 검색 페이지를 세 컴포넌트로 나누었습니다. (검색 인풋, 검색 카테고리, 검색 목록)
2. 검색 인풋, 검색 카테고리 컴포넌트는 생성만 해두었습니다.
3. 검색 목록 컴포넌트에 모든 오픈 채팅방 목록을 불러와 보여주었습니다. (디자인 X)
4. 변경된 환경 변수 이름을 적용하였습니다.
> Feat : 모든 오픈 채팅방 목록 화면에 보여주기 

- Components/Search/SearchOpenChat.tsx
closed #13
검색 기능에 아래 두 가지 기능을 추가하였습니다.
1. 검색된 내용이 없는 문구를 보여주기
2. 엔터를 눌렀을 때만 검색하기
> Feat : 오픈 채팅방 목록 검색 세부 기능 추가

- Components/Open/ChatGenerator/ChatGenerator.tsx
- Components/Open/ChatGenerator/ChatGeneratorMenu/ChatGeneratorMenu.tsx
- Components/Open/ChatList/ChatList.tsx
- app/open/page.tsx
close #23 open page 환경 변수 에러로 쿠키로 대체
쿠키를 accessToken에 저장할 수 있게 돼서 환경 변수 대신 쿠키로 대체하였음
> Feat : 환경변수 사용 X, 쿠키로 대체 pr

- Components/Search/OpenChatPicture.tsx
- Components/Search/OpenChatText.tsx
- Components/Search/SearchOpenChat.tsx
- Components/Search/ShowAllOpenChat.tsx
- app/globals.css
- app/search/search.utils.ts
> Feat : 오픈 채팅방 검색 페이지 디자인

- Components/Common/Header.tsx
- Components/Common/ProfileModal.tsx
- Components/Search/SearchOpenChat.tsx
- Components/Search/ShowSearchedFriend.tsx
- Components/Users/FriendProfiles.tsx
- Components/Users/MyProfile.tsx
- Components/Wrapper.tsx
- app/searchmychat/searchmychat.utils.ts
- app/users/page.tsx
- app/users/users.type.ts
- app/users/users.utils.ts
- next.config.js
close #27 
- 헤더에 서치바로 넘어가는 링크를 달았습니다(유저/톡방 서치바, 참가가능한 오픈톡방 서치바)
- 유저/톡방 서치바는 더보기 기능을 추가하였습니다
- 컨플릭트 해결했습니다
> Feat : 이미지 네비게이션 추가, 유저/톡방 서치바 추가 pr

- Components/Search/OpenChatModal.tsx
- Components/Search/OpenChatText.tsx
- Components/Search/SearchOpenChat.tsx
- Components/Search/ShowAllOpenChat.tsx
- app/search/search.constant.ts
- app/search/search.type.ts
- app/search/search.utils.ts
- types/index.ts
close #35
SearchOpenChat.tsx 컴포넌트의 search(userInput, allOpenChat, setSearchedChats); 타입 에러를 해결하였습니다.
> Fix: allOpenChat 타입 에러 해결 

- Components/Chat/ChatRoom.tsx
- app/chat/[id]/page.tsx
> Feat : 소켓으로 채팅방 구현 (지훈) 

- Components/Chat/ChatHeader.tsx
- Components/Chat/Chats.tsx
- Components/Chat/RenderChats.tsx
- Components/Search/OpenChatModal.tsx
- types/index.ts
> Feat : 소켓으로 채팅방 구현

- Components/Users/ProfileModal.tsx
> Fix : 빌드 오류 수정 pr

- app/chat/[id]/page.tsx
> FIx: 채팅 빌드 에러 해결

- Components/Chat/ChatRoom.tsx
- Components/Chat/RenderChats.tsx
- Components/Search/OpenChatModal.tsx
- app/error.tsx
- app/not-found.tsx
> Feat: 채팅방 사용자 입장 및 나가기 기능 추가

- Components/Chat/ChatRoom.tsx
> Fix: Socket 이전메시지 버그 해결

- Components/Chat/Chats.tsx
> feat: 메세지 전송 시간 기능 추가

- Components/Users/FriendProfiles.tsx
- Components/Users/MyProfile.tsx
- app/users/page.tsx
- public/icon_gray_dot.svg
- public/icon_green_dot.svg
close #75 
Users 페이지 디자인 작업 완료했습니다
폰트랑 색상만 적용되면 디자인 시안과 동일해질 것 같습니다
> Feat : Users 페이지 디자인

- Components/Chat/ChatHeader.tsx
- Components/Chat/ChatRoom.tsx
- Components/Chat/Chats.tsx
- Components/Chat/RenderChats.tsx
- tailwind.config.ts
> Feat: 채팅방 디자인 수정 및 기능 추가

- app/profile/[id]/page.tsx
close #86
Fix : 1:1 채팅시 오픈채팅방 참여 막기
> Fix : 1:1 채팅시 오픈채팅방 참여 막기

- README.md
> Feat: README.md 1차 작성

- .prettierignore
- README.md
> Feat: README.md 2차 작성

- README.md
- tailwind.config.ts
> Feat: README.md 3차 작성 및 배포 스타일 적용 해결

- middleware.ts
- package-lock.json
- package.json
> Feat : 버젼 다운그레이드 / 미들웨어 적용 해제

- middleware.ts
- package-lock.json
- package.json
Reverts MOVIEJOJO7/cat-talk#104
> Revert "Feat : 버젼 다운그레이드 / 미들웨어 적용 해제" pr

- Components/Chat/ChatRoom.tsx
> Fix: 채팅 들어가과 나가기 에러 해결

- Components/Search/OpenChatModal.tsx
> Fix: 오픈 채팅방 이미지 깨지는 문제 해결

- tailwind.config.ts
close #111
배포 tailwind CSS 스타일링 적용 안되는 오류 수정
config 오탈자 수정
> Fix : 배포 tailwind CSS 스타일링 적용 안되는 오류 수정

- app/users/page.tsx
> Fix : users 페이지 스크롤 기능 추가

- README.md
> Feat: README.md 업데이트

- README.md
> Feat: README 업데이트

- README.md
> Feat: README 마무리

- README.md
> Feat: README.md 최종

- Components/Chat/ChatHeader.tsx
- Components/Chat/RenderChats.tsx
> Faet: 헤더 fixed 디자인 추가

- Components/Chat/Chats.tsx
> Fix: 프로필 사진 디자인 수정
